### ISSUE TITLE
Remove copyrighted material

### ISSUE THREAD

**Issue by faroit** [thejasvibr/bat_beamshapes#1]
I didn't check it in detail but the directory https://github.com/thejasvibr/bat_beamshapes/tree/dev/beamshapes/workshop seems to contain copyright protected material from books. If that is the case, this material should be removed from the repo.

**Comment by thejasvibr** [comment]
Hi @faroit , thanks for your message. 
I've now cleaned up the repo and gotten rid of the copyrighted material and removed some non-active branches too. Hope this is okay now?

**Comment by faroit** [comment]
i guess you have to use a tool like https://rtyley.github.io/bfg-repo-cleaner/ to rewrite the git history to remove the files from the history completely

**Comment by thejasvibr** [comment]
BFG-repo-cleaner worked flawlessly - thanks for the suggestion! 

I've removed all copyrighted PDFs, and also some plot images from the test repo - as far as I see now there don't seem to be any more problematic files?

**Comment by faroit** [comment]
Great!
