### ISSUE TITLE
DOC: don't use italic for names in math

### ISSUE THREAD

**Issue by hagenw** [thejasvibr/bat_beamshapes#10]
When using names as variables or as subscripts in math they should not be in italic, e.g.

![image](https://user-images.githubusercontent.com/173624/137478537-3de66d8a-312e-477c-ba72-f5e89c31865b.png)

which most likely has the corresponding code:

```latex
/frac{v_{sound}}{frequency}
```
this should be changed to
```latex
/frac{v_/text{sound}}{/text{frequency}}
```

**Comment by thejasvibr** [comment]
Docs fixed to include non-italicised subscripts
