### ISSUE TITLE
DOC: table of contents looks broken

### ISSUE THREAD

**Issue by hagenw** [thejasvibr/bat_beamshapes#11]
Related to https://github.com/openjournals/joss-reviews/issues/3740

The gap between the caption and the actual sections is too big and it is very hard to relate the sections to the right cpations:

![image](https://user-images.githubusercontent.com/173624/137478848-5d582906-5db8-4ea4-84a8-9a0546476bd4.png)

**Comment by thejasvibr** [comment]
This seems to be an active issue with the sphinx_rtd_theme  ([issue link](https://github.com/readthedocs/sphinx_rtd_theme/issues/1029)). Not sure what I can do to fix it right now - will search around for some time to see if there are any fixes.

**Comment by hagenw** [comment]
It's fixed in the latest version of the docs:

![image](https://user-images.githubusercontent.com/173624/141095784-1aabbaeb-b643-417b-a329-31824b09a997.png)

**Comment by faroit** [comment]
@hagenw can this be closed?

**Comment by hagenw** [comment]
Yes, but I don't have the rights to close it.

**Comment by hagenw** [comment]
I have the rights, sorry ;)
