### ISSUE TITLE
Unit tests should indicate the code coverage

### ISSUE THREAD

**Issue by hagenw** [thejasvibr/bat_beamshapes#12]
Related to https://github.com/openjournals/joss-reviews/issues/3740

Test packages like `pytest` usually provide the possibility to measure the code coverage of the tests. A code coverage of 100% does not mean the code is really well enough tested, but at least it is an indication that the developers have worked on the tests.

At the moment I don't see an easy presentation of the code coverage for the unit tests performed in this package. Would be nice if this could be added at least to the output in the command line when running the tests.

**Comment by thejasvibr** [comment]
Did not find a direct way to estimate code coverage in the unittest package. Did find the [coverage](https://coverage.readthedocs.io/en/6.0.2/index.html) package, and have included steps to estimate code coverage in CONTRIBUTING.md. 

Hope this resolves this issue?

**Comment by hagenw** [comment]
As I only use `pytest` I cannot directly advice how to use `coverage` with `unittest`.
I followed the steps you mentioned in `CONTRIBUTING` and get:

```bash
$ python -m unittest
...
----------------------------------------------------------------------
Ran 6 tests in 399.609s

OK

$ coverage report
No data to report.
```
So, it does not work directly. Do I have to do another step?

**Comment by thejasvibr** [comment]
There was a missing step, which was to run the unit-tests through the ```coverage``` package (``` coverage run -m unittest discover ```). Have added it now as [70da621](https://github.com/thejasvibr/bat_beamshapes/commit/70da621b228226961d71d6cf6115723fd50d196b). 

Hope the coverage reports provide sensible output now?

**Comment by hagenw** [comment]
Thanks, it is now working for me.

**Comment by hagenw** [comment]
```bash
$ coverage report
Name                                             Stmts   Miss  Cover
--------------------------------------------------------------------
beamshapes/__init__.py                               5      0   100%
beamshapes/cap_in_sphere.py                         76     34    55%
beamshapes/piston_in_infinite_baffle.py             18      0   100%
beamshapes/piston_in_sphere.py                     144     12    92%
beamshapes/piston_in_sphere_flint.py               168    165     2%
beamshapes/point_source_on_a_sphere.py              26      0   100%
beamshapes/special_functions.py                      9      0   100%
beamshapes/tests/__init__.py                         0      0   100%
beamshapes/tests/test_osccapsphere.py               41      3    93%
beamshapes/tests/test_pistoninfbaffle.py            32      1    97%
beamshapes/tests/test_pistoninsphere_mpmath.py      83      2    98%
beamshapes/tests/test_pistoninsphereflint.py        57     42    26%
beamshapes/tests/test_pointsourcesphere.py          49      1    98%
beamshapes/utilities.py                              8      1    88%
beamshapes/version.py                                1      0   100%
--------------------------------------------------------------------
TOTAL                                              717    261    64%
```

**Comment by thejasvibr** [comment]
Good to know. Closing issue as problem has been resolved.
