### ISSUE TITLE
Cannot run Oscillating cap of a sphere example

### ISSUE THREAD

**Issue by hagenw** [thejasvibr/bat_beamshapes#16]
When running the code manually from the example at https://beamshapes.readthedocs.io/en/latest/gallery_examples/cap_sphere.html

It fails with:

```
FileNotFoundError: [Errno 2] No such file or directory: 'fig12-17.csv'
```

**Comment by hagenw** [comment]
Related to https://github.com/openjournals/joss-reviews/issues/3740

**Comment by thejasvibr** [comment]
Removed the reference to an external file as it anyway didn't serve much of a purpose. Modified version runs without error when copy-pasted from page.
