### ISSUE TITLE
Getting division by zero warnings for Piston in an infinite baffle example

### ISSUE THREAD

**Issue by hagenw** [thejasvibr/bat_beamshapes#17]
When manually running the code from https://beamshapes.readthedocs.io/en/latest/gallery_examples/pistoon_inf_baffle.html
I get the following output four times:

```
RuntimeWarning: divide by zero encountered in log10
```

this might not be a big deal, but for examples included in the official documentation I would not expect to get such warnings.

**Comment by hagenw** [comment]
Related to https://github.com/openjournals/joss-reviews/issues/3740

**Comment by thejasvibr** [comment]
Fixed by [eb6b4](https://github.com/thejasvibr/bat_beamshapes/commit/eb6b40279790c5d3314edd52bda47933c87a894d) .
