### ISSUE TITLE
Cannot reproduce result of Piston in an infinite baffle example

### ISSUE THREAD

**Issue by hagenw** [thejasvibr/bat_beamshapes#18]
When running manually the code from https://beamshapes.readthedocs.io/en/latest/gallery_examples/pistoon_inf_baffle.html

I get as result

![Figure_1](https://user-images.githubusercontent.com/173624/137482122-e850b597-354f-42e3-a20b-bf4df30c847e.png)

whereas in the documentation I see

![image](https://user-images.githubusercontent.com/173624/137482167-58b22ba1-bf9e-40bb-b2d3-384f586826d1.png)

**Comment by hagenw** [comment]
Related to https://github.com/openjournals/joss-reviews/issues/3740

**Comment by thejasvibr** [comment]
Thanks for pointing out this issue. It was a typo (the output is already the relative off/on axis levels in dB. The example code was taking the dB output once more and 'dB-fying' it again. Deleted, and displayed plot is reproduced.

**Comment by hagenw** [comment]
Thanks, I can confirm that I now also get

![piston-shape](https://user-images.githubusercontent.com/173624/139209673-6b339092-af9d-4081-a15a-ab4c628cef4e.png)

which is identical with the updated documentation page:

![image](https://user-images.githubusercontent.com/173624/139209758-22ad952b-ef5f-4187-9d36-d1f43dc5c114.png)
