### ISSUE TITLE
Package is not pip-installable

### ISSUE THREAD

**Issue by nils-werner** [thejasvibr/bat_beamshapes#2]
Hi, this issue is related to your submission to JOSS, [#3740](https://github.com/openjournals/joss-reviews/issues/3740).

I have noticed that your package is not easily pip-installable, i.e.

```
git clone https://github.com/thejasvibr/bat_beamshapes.git
pip install -e bat_beamshapes
```

fails with

```
    ERROR: Command errored out with exit status 1:
     command: /Users/nwerner/Projekte/beamshapes/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/nwerner/Projekte/beamshapes/bat_beamshapes/setup.py'"'"'; __file__='"'"'/Users/nwerner/Projekte/beamshapes/bat_beamshapes/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/gf/gn2yxq511p77gzs2gsn4gp2w0000gn/T/pip-pip-egg-info-b4i9yk__
         cwd: /Users/nwerner/Projekte/beamshapes/bat_beamshapes/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/nwerner/Projekte/beamshapes/bat_beamshapes/setup.py", line 3, in <module>
        import beamshapes
      File "/Users/nwerner/Projekte/beamshapes/bat_beamshapes/beamshapes/__init__.py", line 8, in <module>
        from beamshapes.piston_in_sphere import piston_in_sphere_directivity
      File "/Users/nwerner/Projekte/beamshapes/bat_beamshapes/beamshapes/piston_in_sphere.py", line 34, in <module>
        from joblib import Parallel, delayed
    ModuleNotFoundError: No module named 'joblib'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I see that you have posted different installation instructions using a `requirements.txt` file, but since you are planning to release the package to PyPI, plain pip-installability will eventually become a requirement. Therefore I'd recommend you to fix this.

**Comment by thejasvibr** [comment]
Thanks a lot @nils-werner  for the raised issues, and helpful feedback. Will get back to resolving and replying to each over the coming week or two!

**Comment by thejasvibr** [comment]
pip installation doesn't work: 

```
from joblib import Parallel, delayed
    ModuleNotFoundError: No module named 'joblib'
```
possible error in ```import beamshapes``` in setup.py.
The __init__.py hase the ```__version__``` number, but also imports other modules that require dependencies.

**Comment by thejasvibr** [comment]
The package is now locally installable, and also on PyPi for general installation. Have tested it on two separate Windows systems, will try it out on a Linux at some point - hope it will work there too.
