### ISSUE TITLE
Documentation badge on the README points to wrong project

### ISSUE THREAD

**Issue by hagenw** [thejasvibr/bat_beamshapes#21]
In the README we have the following badges:

![image](https://user-images.githubusercontent.com/173624/139208139-54519a1a-407f-4e4a-b202-bde396f1ced0.png)

If you click on "docs | passing" you will end up on https://batracker.readthedocs.io/ and not https://beamshapes.readthedocs.io/

**Comment by thejasvibr** [comment]
thanks @hagenw  for pointing this out! Both the Travis CI and RTD badges were off-target. 

Re-checked that all badges lead to the right pages as of [54d22b4](https://github.com/thejasvibr/bat_beamshapes/commit/54d22b45c330d3edcb9a54ad64277dc553d8d220)
