### ISSUE TITLE
Return types in API documentation inconsistent?

### ISSUE THREAD

**Issue by hagenw** [thejasvibr/bat_beamshapes#22]
Related to https://github.com/openjournals/joss-reviews/issues/3740

When looking at the API documentation at https://beamshapes.readthedocs.io/en/latest/source_models.html
you will find

![image](https://user-images.githubusercontent.com/173624/141095254-8e266ab5-b082-4baa-a784-68c0078e4e3c.png)

Does this really don't have any return value?

In addition, we have a few that return a tuple, but the first entry is specified as `None`

![image](https://user-images.githubusercontent.com/173624/141095380-bd47d4f2-d3d8-494f-a65f-309b0fe5f329.png)

is this the desired behavior?

For others the "Return Type" is explicitly given

![image](https://user-images.githubusercontent.com/173624/141095542-f5447eba-85ec-418f-88c0-edde93f1599d.png)

---

This all makes it hard for the reader to know what to expect from the functions without trying them out.

**Comment by thejasvibr** [comment]
Have addressed this issue. All documented functions now have the returned object and the types explicitly stated as of [ed2532](https://github.com/thejasvibr/bat_beamshapes/commit/ed25329abb46e480ed261593813231995f7a01ab). 

Hope this sorts the deficiency in [the docs](https://beamshapes.readthedocs.io/en/latest/source_models.html)?

**Comment by hagenw** [comment]
We still have the returned tuple with `None` as first entry

![image](https://user-images.githubusercontent.com/173624/145387336-509f7cab-8983-44e4-a34e-fdf67c21f3db.png)

How should I interpret this as a user? Is the first return value meaningless and I should call the function with:

```python
_, beamshapes = beamshapes.piston_in_infinite_baffle.piston_in_infinite_baffle_directivity(angles, params)
```

**Comment by thejasvibr** [comment]
Yes, this is how it is intended (return variable name corrected to ```dtheta_by_dzero``` in the [latest commit](https://github.com/thejasvibr/bat_beamshapes/commit/4ef42aef0e0848275abd34c56e72e840378d53e6)). 

The first returned object of *<source_model>_directivity* function is intended to be a ```None``` OR a matrix calculated for source models whose directivities take a long time to run. If the directivity needs to be calculated again for a new set of angles, the returned matrix can be used. 

The first returned object is ```None``` for fast running directivities (piston in infinite baffle, cap of a sphere, point source on a sphere) - while it is[ a matrix for the piston in a sphere](https://beamshapes.readthedocs.io/en/latest/source_models.html#beamshapes.piston_in_sphere.piston_in_sphere_directivity). In general, as more time consuming source models are added, I expect the user will find the calculated matrix a major time-saver.

For example - if one were to run a piston in a sphere - it'd typically take 2-5 mins to get directivities for one set of angles:

```
import beamshape
matrix_coefs, set1_directivities = beamshape.piston_in_sphere_directivity(set1_angles, params) # this takes 2-5 min for e.g.

# now say we want to calculate the directivity for another set of angles - the calculation happens very quickly 
#because we include the pre-calculated matrix
_, set2_directivities = beamshape.piston_in_sphere_directivity(set2_angles, params, A_n=matrix_coefs)
```
