### ISSUE TITLE
Gitignore seems incomplete

### ISSUE THREAD

**Issue by nils-werner** [thejasvibr/bat_beamshapes#23]
You have a non-empty `dist/` directory in your repo, which probably should be ignored. Have a look at the [Python.gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore) file to see what may be missing.

**Comment by thejasvibr** [comment]
Good point. Have added the template file+folder formats into my .gitignore - yet, there's some other issue which prevents me from removing the ```dist``` folder with a simple ```git rm --cached dist/*``` command. Will need further probing to see why it is not disappearing from the VC.

**Comment by thejasvibr** [comment]
Taken care of. ```dist``` folder removed from VC as of [9d96](https://github.com/thejasvibr/bat_beamshapes/commit/9d9616d0387dedf81e74da8f751d435aaa5a62ca). Just needed to run a ```git clean -f``` and the problem was solved.
