### ISSUE TITLE
Link to documentation broken

### ISSUE THREAD

**Issue by nils-werner** [thejasvibr/bat_beamshapes#4]
Hi, this issue is related to your submission to JOSS, [#3740](https://github.com/openjournals/joss-reviews/issues/3740).

Currently your `README` links to the docs under

```
https://github.com/thejasvibr/bat_beamshapes/blob/dev/beamshapes.rtfd.io
```

while I believe the correct address should be

```
https://beamshapes.rtfd.io
```

Also to improve visibility of the docs I would also suggest to add this URL to the Repo info, and possibly also add an [RDT badge](https://docs.readthedocs.io/en/stable/badges.html)

**Comment by thejasvibr** [comment]
Thanks for pointing it out. Have updated the broken link, and also included the RTD docs badge to signal latest status.
