### ISSUE TITLE
API docs output broken?

### ISSUE THREAD

**Issue by nils-werner** [thejasvibr/bat_beamshapes#5]
Hi, this issue is related to your submission to JOSS, [#3740](https://github.com/openjournals/joss-reviews/issues/3740).

In some places the API docs appear to have broken output: e.g. on https://beamshapes.readthedocs.io/en/latest/source_models.html#beamshapes.point_source_on_a_sphere.d_theta_func it looks like this:

![Screenshot 2021-09-21 at 13 26 54](https://user-images.githubusercontent.com/88704/134162652-af00eed2-588a-4966-8011-1e814ce090aa.png)

Is this on purpose?

**Comment by thejasvibr** [comment]
Hi,
It does look messy indeed! This isn't really on purpose, but rather the side effect of having SymPy-derived lambda-s using [lambdify](https://docs.sympy.org/latest/modules/utilities/lambdify.html). SymPy-derived lambdas convert math expressions into functions that accept concrete numerical inputs. The messy looking output is the underlying code implementation of the math expression that is returned on doing eg. ```help(d_theta_func)```. 

The whole package has a lot of such Sympy-derived lambdas - do you think it's better to get rid of them for visual cleanliness?

**Comment by hagenw** [comment]
I also thought your math output is simply broken in the API docs.

I would recommend to find a way to render the math output as math.

Also the there are lots of `:` without content afterwards and one wonders if the  `_lambdifygenerated()` is part of the API or something used to generate the documentation.

So in general I would recommend to revisit the API documentation.

**Comment by thejasvibr** [comment]
I haven't found a way to render the ```lambdify``` output as math. Even if the math rendering did work out - it'd be a lot of math equations getting in the way of the broad picture of how the package works from a software point?

I reconsidered what is relevant enough to be on the online API, and have thus trimmed the functions whose documentations will be hosted online. 

Hope this version (as of [52d8021](https://github.com/thejasvibr/bat_beamshapes/commit/52d80210570881d3169eba4c83b1b75bd3b70cad)) of the  API docs is clearer?

**Comment by hagenw** [comment]
If I understand it correctly you decided now against showing the math as it is complicated and will not help the user, correct?
I think this is fine as you provide references to the underlying math anyway.

There is still one function left in the API that looks as before:

![image](https://user-images.githubusercontent.com/173624/139212070-10bea503-a141-419b-a768-e131f50650fd.png)

Is this on purpose, or did you forgot to change it there?

**Comment by thejasvibr** [comment]
I had initially left the weird lambda formatting to keep consistency in which function's docs were displayed - I [have now fixed the formatting issue](https://beamshapes.readthedocs.io/en/latest/source_models.html#point-source-on-a-sphere).

I managed to solve the formatting issue by realising a lambdified expression is after all a lambda object. Thanks to [this SO contribution](https://stackoverflow.com/a/50371184/4955732), I could add docstrings by separately setting the lambda functions ```.__doc__``` attribute. The output is now 'standard' looking as of [this commit](https://github.com/thejasvibr/bat_beamshapes/commit/74636abfda0c043f4dceb2a6bf0f991343747172).

**Comment by hagenw** [comment]
Thanks, I'm fine with your fix.

**Comment by faroit** [comment]
@nils-werner can this be closed?

**Comment by nils-werner** [comment]
Yes, they're looking great!
