### ISSUE TITLE
Docs are very terse

### ISSUE THREAD

**Issue by nils-werner** [thejasvibr/bat_beamshapes#7]
Hi, this issue is related to your submission to JOSS, [#3740](https://github.com/openjournals/joss-reviews/issues/3740).

I have noticed the docs for your library are very terse. While you do have a section that roughly explains the concept of a directivity pattern, you very quickly dive into technicalities like parameters and specific patterns. This makes it really hard for people inside and outside of your field to quickly understand the purpose of this library and what problems it solves.

I would recommend expanding on these sections, using more text and simpler language.

Also, the implemented directivity patterns are [only listed by name and a single figure each](https://beamshapes.readthedocs.io/en/latest/general_intro.html#source-models). Just from these figures, I was unfortunately not able to understand the actual shape and its properties. Again, I would recommend expanding on these sections, and maybe more figures.

**Comment by hagenw** [comment]
I agree and would also recommend to improve the introduction of the package.

**Comment by thejasvibr** [comment]
As of [52d8021](https://github.com/thejasvibr/bat_beamshapes/commit/52d80210570881d3169eba4c83b1b75bd3b70cad) Have worked on adding brief model descriptions and background on their meaning.

Hope this version of the docs is clearer and provides more background?

**Comment by faroit** [comment]
@nils-werner are these changes sufficient?

**Comment by nils-werner** [comment]
Yes, the docs are much better now, thanks! (you could also link to them in your repo settings)
