### ISSUE TITLE
Unittests are very dense

### ISSUE THREAD

**Issue by nils-werner** [thejasvibr/bat_beamshapes#8]
Hi, this issue is related to your submission to JOSS, [#3740](https://github.com/openjournals/joss-reviews/issues/3740).

This is more a personal remark and wouldn't be a reason for rejection.

I noticed that your unit test code is very dense and contains a lot of boilerplate, which makes it really hard to understand the tests. I believe a useful unittest should not only successfully test a feature, but also be simple enough so that developers can quickly understand what feature is being tested (i.e. to recognize holes in test coverage).

To that end I would recommend cleaning up and slimming down the test code, and potentially moving to a modern test framework, like [pytest](https://docs.pytest.org/).

**Comment by thejasvibr** [comment]
Hi @nils-werner , thanks for your comment on the tests. 
Admittedly the tests in the repo are do have some boilerplate related to loading the ground-truth data and testing each parameter set - and would need time for a future contributor (or myself) to get into.

About switching to ```pytest```  and re-factoring the tests, I have considered these options, and finally realised my current project + funding timeline means it won't be possible to achieve within the next few months. 

I do see the power of using a another testing framework, and the importance of having minimal boilerplate - and will consider  implementing these over a longer time-scale when possible. Hope this is okay?

**Comment by nils-werner** [comment]
Yes, this is OK. As I said, it wouldn't be a reason for rejection.
