### ISSUE TITLE
No documentation on how to run tests

### ISSUE THREAD

**Issue by hagenw** [thejasvibr/bat_beamshapes#9]
This is related to https://github.com/openjournals/joss-reviews/issues/3740

I would recommend to add a section to `CONTRIBUTING` or `README` on how to execute the unit tests.

I also found `beamshapes/tests/testing.md`, which should maybe also linked to at some place.

I did execute the following:

```bash
$ python -m unittest
```

Hope this is the desired way to run the tests?

**Comment by thejasvibr** [comment]
Hi @hagenw ,thanks for the detailed issues. Much to clarify and fix clearly.
Will get down to working on them over the course of the next month!

**Comment by thejasvibr** [comment]
Have included instructions to run and write tests with links as of this commit.

**Comment by hagenw** [comment]
Thanks for adding this.

The formatting is slightly broken:

![image](https://user-images.githubusercontent.com/173624/139208571-f82d788e-493e-40c7-8d25-4ddc6a366aca.png)
